FROM prestabase:latest

# Init Scripts
COPY config/php.ini /usr/local/etc/php/
COPY config/000-default.conf /etc/apache2/sites-enabled/
COPY config/apache2.conf /etc/apache2/
COPY config/bashrc /root/.bashrc
COPY example-modules /var/www/html/example-modules

# Local PS Zip
COPY prestashop_8.1.6.zip /tmp/prestashop.zip

COPY config/install_everything.sh /tmp/
CMD ["/tmp/install_everything.sh"]