version: '3'
services:
  mysql:
    container_name: prestasql
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
    networks:
      - prestashop_network
    volumes:
      - ./config/70-prestashop.cnf:/etc/mysql/mariadb.conf.d/70-prestashop.cnf

  prestashop:
    container_name: prestashop
    image: prestadevel:latest
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8080:80
      - 2222:22
      - 6688:6688
    volumes:
      - ./modules/easybackup:/var/www/html/modules/easybackup:rw
      - ./logs/apache:/var/log/apache2:rw
      - ./logs/prestashop:/var/www/html/var/logs:rw
    environment:
      ADMIN_MAIL: demo@prestashop.com
      ADMIN_PASSWD: prestashop_demo
      DB_NAME: prestashop
      DB_PASSWD: admin
      DB_PORT: 3306
      DB_PREFIX: ps_
      DB_SERVER: prestasql
      DB_USER: root
      PS_ERASE_DB: 0
      PS_INSTALL_DB: 0
      INIT_SCRIPTS_DIR: /tmp/init-scripts
      PS_DEV_MODE: 1
      PS_DOMAIN: 10.11.12.100:8080
      PS_FOLDER_ADMIN: admin1
      PS_FOLDER_INSTALL: installed
      PS_FOLDER: /var/www/html
      PS_INSTALL_AUTO: 1
      PS_LANGUAGE: en
    networks:
      - prestashop_network

  loki:
    image: grafana/loki:2.0.0
    container_name: loki
    networks:
      - prestashop_network
    ports:
      - "3100:3100"
    volumes:
      - ./config/loki-config.yaml:/etc/loki/local-config.yaml
      - ./loki:/loki

  promtail:
    image: grafana/promtail:2.0.0
    container_name: promtail
    networks:
      - prestashop_network
    volumes:
      - ./config/promtail-config.yml:/etc/promtail/promtail.yml
      - ./logs/apache:/var/log/apache2
      - ./logs/prestashop:/var/www/html/var/logs
    command: -config.file=/etc/promtail/promtail.yml

  grafana:
    image: grafana/grafana:7.3.1
    container_name: grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin    
    networks:
      - prestashop_network
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources


networks:
  prestashop_network: