version: '3'
services:
  mysql:
    container_name: prestasql
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
    networks:
      - prestashop_network
    volumes:
      - ./config_files/70-prestashop.cnf:/etc/mysql/mariadb.conf.d/70-prestashop.cnf

  prestashop:
    container_name: prestashop
    image: prestadevel:latest
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8080:80
      - 2222:22
      - 6688:6688
    volumes:
      - ./init-scripts:/tmp/init-scripts:ro
      - ./modules/easybackup:/var/www/html/modules/easybackup:rw
      - apache_logs:/var/log/apache:rw
      - prestashop_logs:/var/www/html/var/logs:rw
    environment:
      ADMIN_MAIL: demo@prestashop.com
      ADMIN_PASSWD: prestashop_demo
      DB_NAME: prestashop
      DB_PASSWD: admin
      DB_PORT: 3306
      DB_PREFIX: ps_
      DB_SERVER: prestasql
      DB_USER: root
      PS_ERASE_DB: 0
      PS_INSTALL_DB: 0
      INIT_SCRIPTS_DIR: /tmp/init-scripts
      PS_DEV_MODE: 1
      PS_DOMAIN: 10.11.12.100:8080
      PS_FOLDER_ADMIN: admin1
      PS_FOLDER_INSTALL: installed
      PS_FOLDER: /var/www/html
      PS_INSTALL_AUTO: 1
      PS_LANGUAGE: en
    networks:
      - prestashop_network

  grafana:
    container_name: grafana
    image: grafana/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin    
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      # - ./config_files/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
       
    depends_on:
      - loki
    networks:
      - prestashop_network

  loki:
    container_name: loki
    image: grafana/loki:2.7.1
    ports:
      - "3100:3100"
    volumes:
      - ./config_files/loki_config:/etc/loki
      - ./loki/data:/loki:rw
      - ./loki/wal:/wal:rw
      - apache_logs:/var/log/apache:ro
      - prestashop_logs:/var/log/prestashop:ro
    networks:
      - prestashop_network

volumes:
  grafana_data:
  apache_logs:
  prestashop_logs:
  loki_data:
    driver: local
networks:
  prestashop_network:
