server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: apache_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: apache
          __path__: /var/log/apache2/*.log

  - job_name: prestashop_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: prestashop
          __path__: /var/www/html/var/logs/*.log
